---
title: "PSET 2 Dev and Data"
author: "Matthew Zhao"
date: "11/5/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, warning=F, message=F}
library(tidyverse)
library(haven)
library(broom)
library(ggplot2)
library(fixest)
library(stargazer)
library(xtable)
options(scipen=999)
```

# Q2

```{r}
savings_dta <- read_dta("pset2_data/dataset_savings.dta")

savings_df <- savings_dta %>%
  mutate(active = ifelse(first6_num_trans_savings > 1, TRUE, FALSE),
         treatment_bg_boda = treatment*bg_boda,
         active_bg_boda = active*bg_boda,
         bg_boda_wave2 = (bg_boda & wave2),
         bg_malevendor_wave2 = (bg_malevendor & wave2),
         bg_malevendor_wave3 = (bg_malevendor & wave3),
         treament_bg_malevendor = treatment*bg_malevendor,
         active_bg_malevendor = active*bg_malevendor,
         literate_swahili = ifelse((bg_kis_read == 1 & bg_kis_write ==1),
                                   1,
                                   NA),
         literate_swahili = ifelse((bg_kis_read ==0 | bg_kis_write == 0), 
                                   0,
                                   literate_swahili))
```
```{r}
bal_controls = c(
     "wave1",
     "wave2",
     "wave3",
     'bg_boda',  
     'bg_age'  ,
     'bg_married',  
     'bg_num_children',  
     'bg_educ',  
     'literate_swahili',
     'bg_rosca',  
     'bg_rosca_contrib_lyr',  
     'bg_animalsvalue',  
     'bg_totalinc_lastweek',  
     'bg_loan_bank',  
     'bg_loan_friend',  
     'bg_healthstatus',  
     'per_hard_save',  
     'per_invest_choice2',  
     'per_somewhat_patient',  
     'per_time_consistent',  
     'per_pat_now_impat_later',  
     'per_maximpat',  
     'per_fwd_digit_score2',  
     'per_ravens_matrix',  
     'bg_durvalue_hh',  
     'per_hyperbolic'  
)
```
```{r}
longer_stats <- savings_df %>%
  drop_na(treatment,filled_log) %>%
  mutate_if(is.numeric, ~replace_na(.,mean(., na.rm = TRUE))) %>%
  select(bg_gender,treatment,all_of(bal_controls)) %>%
  pivot_longer(cols=bal_controls,
               names_to='name',values_to='value')
grp_means <- longer_stats %>%
  group_by(bg_gender,treatment,name) %>%
  summarise(means = mean(value),
            .groups='keep') %>%
  mutate(bg_gender = ifelse(bg_gender==0,'Female','Male'),
         treatment = ifelse(treatment==0,'Control','Treatment')) %>%
  pivot_wider(names_from=c(treatment,bg_gender),values_from=means,
              names_sep=', ')
pvals <- longer_stats %>%
  group_by(bg_gender,name) %>%
  summarise(pval = t.test(value ~ treatment)$p.value,
            .groups='keep') %>%
  mutate(bg_gender = ifelse(bg_gender==0,
                            'pval_diff_female',
                            'pval_diff_male')) %>%
  pivot_wider(names_from=bg_gender,values_from=pval)
smy <- left_join(grp_means,pvals,by='name')
smy <- smy[match(bal_controls,smy$name),]
q2_tab <- xtable(smy)
align(q2_tab) <- xalign(q2_tab)
display(q2_tab) <- xdisplay(q2_tab)
print(q2_tab, include.rownames=FALSE)
```


## Q4

```{r fig.dim=c(5,4), out.width='75%', fig.align='center'}
q4 <- savings_df %>%
  filter(treatment == 1) %>%
  drop_na(treatment,first6_num_trans_savings) %>%
  select(first6_num_trans_savings)
ggplot(q4, aes(x=first6_num_trans_savings)) +
  geom_histogram(binwidth = 1) + theme_light() + 
  ggtitle("Transactions in First Six Months") +
  xlab("Number of Transactions") + ylab("Count") +
  theme(plot.title = element_text(family = 'serif', hjust = 0.5, size = 12), 
        axis.title = element_text(family = 'serif', size = 10),
        axis.text = element_text(family = 'serif',size=8))
ggsave(filename = 'q4_hist.png',
           path = 
             "pset2_outputs",
           device = "png",
           width = 15,
           height = 12,
           limitsize = FALSE,
           dpi = 300,
           units = "cm")
```

### Q4c)

```{r table2_odd, results = "asis"}
outcome_variables = c(
    "active",
    "bank\\_savings",
    "animal\\_savings",
    "rosca\\_contrib"
)
q4c <- savings_df %>%
  drop_na(treatment,bg_gender,bg_boda,bg_malevendor,
          wave2,wave3,bg_rosca_contrib_lyr,bg_married,bg_num_children,bg_age,bg_kis_read,
          bg_kis_write,filled_log)
vars <- 'treatment + bg_gender + bg_boda + bg_malevendor + bg_rosca_contrib_lyr + bg_married + bg_num_children + bg_age + bg_kis_read + bg_kis_write + filled_log + wave2 + bg_gender*wave2 + bg_gender*wave2*bg_boda + wave3 + bg_gender*wave3 + bg_gender*wave3*bg_boda'
m1 <- lm(paste('active ~', vars),data=q4c)
m2 <- lm(paste('bank_savings ~', vars),data=q4c)
m3 <- lm(paste('animal_savings ~', vars),data=q4c)
m4 <- lm(paste('rosca_contrib ~', vars),data=q4c)
models <- list(m1,m2,m3,m4)
table2 <- stargazer(models,type='latex',digits=2,dep.var.labels=outcome_variables,
          title='Table 2: Impacts on Savings',keep = c('treatment'),header=F,suppress.errors = T)
```

## Q7)

```{r table2_even, results = "asis"}
vars <- 'treatment + treatment*bg_boda + treatment*bg_malevendor + bg_gender + bg_boda + bg_malevendor + bg_rosca_contrib_lyr + bg_married + bg_num_children + bg_age + bg_kis_read + bg_kis_write + filled_log + wave2 + bg_gender*wave2 + bg_gender*wave2*bg_boda + wave3 + bg_gender*wave3 + bg_gender*wave3*bg_boda'
m1 <- lm(paste('active ~', vars),data=q4c)
m2 <- lm(paste('bank_savings ~', vars),data=q4c)
m3 <- lm(paste('animal_savings ~', vars),data=q4c)
m4 <- lm(paste('rosca_contrib ~', vars),data=q4c)
models <- list(m1,m2,m3,m4)
table2 <- stargazer(models,type='latex',digits=2,
                    dep.var.labels=outcome_variables,title='Table 2: Impacts on Savings',
                    keep=c('treatment','treatment:bg_boda'),
                    header=F,suppress.errors = T)
```

## Q8)

```{r table5, results = "asis"}
cov1 <- c('bg_femalevendor','bg_malevendor','wave2','wave3')
cov2 <- c('bg_educ','literate_swahili','bg_age','bg_married','female_married',
          'malevendor_married','rosca_contribK','bg_animalsvalue',
          'bg_durvalue_hh')
cov3 <- c('per_invest_choice2','per_somewhat_patient','per_hyperbolic',
          'per_pat_now_impat_later','per_maximpat','per_missing')

q8 <- savings_df %>% 
  filter(treatment == 1 & !is.na(inlogs)) %>% 
  rowwise() %>%
  mutate(lntotalplus1 = log(1 + first6_dep_savings),
         female_married = ifelse(bg_gender==0,1,0) * bg_married,
         malevendor_married = bg_malevendor * bg_married,
         rosca_contribK = bg_rosca_contrib_lyr/1000,
         bg_animalsvalue = bg_animalsvalue/1000,
         bg_durvalue_hh = bg_durvalue_hh/1000,
         per_missing = ifelse(
           is.na(per_invest_choice2) | is.na(per_somewhat_patient) |
             is.na(per_hyperbolic) | is.na(per_pat_now_impat_later) | 
             is.na(per_maximpat),1,0)) %>%
  select(lntotalplus1,all_of(cov1),all_of(cov2),all_of(cov3))

m1 <- lm(paste('lntotalplus1 ~', 
               paste(cov1,collapse='+')),data=q8)
m2 <- lm(paste('lntotalplus1 ~', 
               paste(c(cov1,cov2),collapse='+')),data=q8)
m3 <- lm(paste('lntotalplus1 ~', 
               paste(c(cov1,cov2,cov3),collapse='+')),data=q8)
models <- list(m1,m2,m3)
table2 <- stargazer(models,type='latex',digits=2,
                    dep.var.labels=c('Log (1+total deposited in Ksh)'),
                    title='Table 5-Determinants of Account Usage Within Six Months of Account Opening')
```

